[package]
name = "pokemon"
version = "0.1.0"
edition = "2021"
authors = ["Xiang Li <xiang.li@talkdesk.com>"]

[dependencies]
clap = "2.26.0"
colored = "3.0.0"
crossterm = "0.22"
image = "0.23"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
viuer = "0.4"
